version: '3.3'
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=chamados
  app:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
